# Generated by Django 5.2.4 on 2025-09-16 23:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone_e164', models.CharField(blank=True, default='', max_length=32)),
                ('name', models.CharField(blank=True, default='', max_length=120)),
                ('provider', models.CharField(choices=[('CINETPAY', 'CinetPay'), ('FLUTTERWAVE', 'Flutterwave')], max_length=20)),
                ('provider_tx_id', models.CharField(help_text='transaction_id envoyé au PSP', max_length=64)),
                ('provider_ref', models.CharField(blank=True, default='', help_text='référence/numero PSP', max_length=128)),
                ('amount', models.PositiveIntegerField(help_text='montant minoré dans la devise minimale (ex: CDF entiers)')),
                ('currency', models.CharField(default='CDF', max_length=8)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('ACCEPTED', 'Accepté'), ('REFUSED', 'Refusé'), ('CANCELED', 'Annulé'), ('ERROR', 'Erreur')], db_index=True, default='PENDING', max_length=16)),
                ('raw_request', models.JSONField(blank=True, null=True)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('raw_check', models.JSONField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['provider', 'provider_tx_id'], name='payments_pa_provide_19bed5_idx'), models.Index(fields=['status', 'created_at'], name='payments_pa_status_343680_idx')],
                'constraints': [models.UniqueConstraint(fields=('provider', 'provider_tx_id'), name='uniq_provider_tx')],
            },
        ),
    ]
