# Generated by Django 5.2.4 on 2025-08-07 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_partenaire_project_partners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partenaire',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='static/partenaires/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='static/project_images/'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='image',
            field=models.ImageField(upload_to='static/team_images/'),
        ),
    ]
