# Generated by Django 5.2.4 on 2025-08-11 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_document'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
