# Generated by Django 5.2.4 on 2025-08-22 18:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_event_location_event_projects'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partenaire',
            options={'ordering': ('sort_order', 'name')},
        ),
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ('sort_order', 'name')},
        ),
        migrations.AddField(
            model_name='partenaire',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='partenaire',
            name='category',
            field=models.CharField(choices=[('ngo', 'Association / ONG'), ('public', 'Institution publique'), ('company', 'Entreprise'), ('media', 'Média'), ('univ', 'Université'), ('other', 'Autre')], default='other', max_length=12),
        ),
        migrations.AddField(
            model_name='partenaire',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='partenaire',
            name='contact_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='partenaire',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='partenaire',
            name='contribution',
            field=models.TextField(blank=True, help_text='Financement, dons en nature, bénévolat d’entreprise…'),
        ),
        migrations.AddField(
            model_name='partenaire',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partenaire',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partenaire',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='partenaire',
            name='instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='partenaire',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='partenaire',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='partenaire',
            name='slug',
            field=models.SlugField(blank=True, max_length=160, unique=True),
        ),
        migrations.AddField(
            model_name='partenaire',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='partenaire',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partenaire',
            name='tier',
            field=models.CharField(blank=True, choices=[('platinum', 'Platine'), ('gold', 'Or'), ('silver', 'Argent'), ('bronze', 'Bronze'), ('standard', 'Standard')], max_length=10),
        ),
        migrations.AddField(
            model_name='partenaire',
            name='twitter',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='partenaire',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teammember',
            name='department',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='teammember',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='teammember',
            name='expertise',
            field=models.TextField(blank=True, help_text='Domaines d’expertise, mots-clés'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='github',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='joined_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='languages',
            field=models.CharField(blank=True, help_text='Ex: fr, en', max_length=200),
        ),
        migrations.AddField(
            model_name='teammember',
            name='left_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='location',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='teammember',
            name='phone',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='teammember',
            name='pronouns',
            field=models.CharField(blank=True, help_text='Ex: elle/il', max_length=40),
        ),
        migrations.AddField(
            model_name='teammember',
            name='seniority',
            field=models.CharField(blank=True, choices=[('exec', 'Direction'), ('lead', 'Lead'), ('senior', 'Senior'), ('mid', 'Confirmé·e'), ('junior', 'Junior'), ('other', 'Autre')], max_length=12),
        ),
        migrations.AddField(
            model_name='teammember',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teammember',
            name='twitter',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='partenaire',
            name='description',
            field=models.TextField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='partenaire',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='team_images/'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='role',
            field=models.CharField(help_text='Intitulé du poste affiché', max_length=120),
        ),
        migrations.AddIndex(
            model_name='partenaire',
            index=models.Index(fields=['slug'], name='core_parten_slug_31fc70_idx'),
        ),
        migrations.AddIndex(
            model_name='partenaire',
            index=models.Index(fields=['category', 'tier'], name='core_parten_categor_edc8ed_idx'),
        ),
        migrations.AddIndex(
            model_name='partenaire',
            index=models.Index(fields=['is_active', 'sort_order'], name='core_parten_is_acti_620ae3_idx'),
        ),
        migrations.AddIndex(
            model_name='teammember',
            index=models.Index(fields=['slug'], name='core_teamme_slug_76f0c2_idx'),
        ),
        migrations.AddIndex(
            model_name='teammember',
            index=models.Index(fields=['is_active', 'sort_order'], name='core_teamme_is_acti_b449f8_idx'),
        ),
    ]
