# Generated by Django 5.2.4 on 2025-08-25 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_teammemberinvite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VolunteerApplication',
        ),
    ]
