# Generated by Django 5.2.4 on 2025-09-01 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_delete_volunteerapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammemberinvite',
            name='response',
            field=models.CharField(blank=True, choices=[('accepted', 'Accepted'), ('declined', 'Declined')], max_length=16),
        ),
    ]
