# Generated by Django 5.2.4 on 2025-09-01 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_teammemberinvite_response'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='flutterwave', max_length=40)),
                ('tx_ref', models.CharField(max_length=100, unique=True)),
                ('provider_tx_id', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('initiated', 'Initiée'), ('pending', 'En attente'), ('success', 'Réussie'), ('failed', 'Échec'), ('cancelled', 'Annulée')], default='initiated', max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='KES', max_length=6)),
                ('donor_name', models.CharField(blank=True, max_length=120)),
                ('message', models.TextField(blank=True)),
                ('return_url', models.URLField(blank=True)),
                ('webhook_seen', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('donation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='core.donation')),
            ],
            options={
                'indexes': [models.Index(fields=['tx_ref'], name='core_paymen_tx_ref_c9056c_idx'), models.Index(fields=['status'], name='core_paymen_status_04c981_idx')],
            },
        ),
    ]
