# Generated by Django 5.2.4 on 2025-09-05 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_paymenttransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(default='CD', editable=False, max_length=2)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('province', models.CharField(blank=True, default='', max_length=120)),
            ],
            options={
                'verbose_name': 'Ville',
                'verbose_name_plural': 'Villes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SiteStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_users', models.PositiveIntegerField(default=0)),
                ('total_volunteers', models.PositiveIntegerField(default=0)),
                ('total_staff', models.PositiveIntegerField(default=0)),
                ('total_missions', models.PositiveIntegerField(default=0)),
                ('total_signups', models.PositiveIntegerField(default=0)),
                ('total_hours_entries', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
