# Generated by Django 5.2.4 on 2025-09-05 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_city_sitestats'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Appui scolaire', max_length=200)),
                ('beneficiary_name', models.CharField(blank=True, max_length=150)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='stories/education/%Y/%m/')),
                ('quote', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='education_stories', to='core.city')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EducationStoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='stories/education/%Y/%m/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.educationstory')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
