# Generated by Django 5.2.4 on 2025-09-14 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_educationstory_category'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='educationstory',
            new_name='core_educat_categor_b38d9e_idx',
            old_name='core_story_cat_pub_idx',
        ),
    ]
