# Generated by Django 5.2.4 on 2025-09-14 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_educationstory_consent_file'),
        ('core', '0019_rename_core_story_cat_pub_idx_core_educat_categor_b38d9e_idx'),
    ]

    operations = [
    ]
