# Generated by Django 5.2.4 on 2025-08-27 21:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('privacy', 'Politique de confidentialité'), ('terms', 'Conditions d’utilisation'), ('cookies', 'Politique cookies'), ('imprint', 'Mentions légales')], max_length=24)),
                ('locale', models.CharField(default='fr', max_length=8, validators=[django.core.validators.RegexValidator('^[a-z]{2}(-[A-Z]{2})?$')])),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['key', 'locale'],
                'unique_together': {('key', 'locale')},
            },
        ),
        migrations.CreateModel(
            name='LegalVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(help_text='ex: v1.0-2025-08-27', max_length=40)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publié')], default='draft', max_length=12)),
                ('effective_date', models.DateField(blank=True, help_text='Date d’entrée en vigueur', null=True)),
                ('published_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('body_md', models.TextField(blank=True, help_text='Contenu en Markdown (recommandé)')),
                ('body_html', models.TextField(blank=True, help_text='Rendu HTML (généré)')),
                ('change_log', models.TextField(blank=True, help_text='Résumé des changements (public)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='legal.legaldocument')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_legal_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-effective_date', '-published_at', '-id'],
                'unique_together': {('document', 'version')},
            },
        ),
        migrations.CreateModel(
            name='LegalAcceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_acceptances', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acceptances', to='legal.legaldocument')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acceptances', to='legal.legalversion')),
            ],
            options={
                'ordering': ['-accepted_at'],
                'unique_together': {('user', 'version')},
            },
        ),
    ]
