# Generated by Django 5.2.4 on 2025-08-27 21:48

import django.db.models.deletion
import staff.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0013_delete_volunteerapplication'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizationKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, max_length=120)),
                ('token_prefix', models.CharField(db_index=True, max_length=16)),
                ('token_hash', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('level', models.IntegerField(choices=[(10, 'Low'), (20, 'Medium'), (30, 'High'), (40, 'Critical')], default=20)),
                ('allowed_actions', models.JSONField(blank=True, default=list)),
                ('max_uses', models.PositiveIntegerField(blank=True, null=True)),
                ('uses_count', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authkeys_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publié'), ('archived', 'Archivé')], default='published', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missions', to='core.event')),
            ],
            options={
                'ordering': ['start_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='VolunteerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Nom complet')),
                ('phone', models.CharField(max_length=50, verbose_name='Téléphone')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('address_line1', models.CharField(max_length=255, verbose_name='Adresse (ligne 1)')),
                ('address_line2', models.CharField(blank=True, max_length=255, verbose_name='Complément d’adresse')),
                ('city', models.CharField(max_length=120, verbose_name='Ville')),
                ('state', models.CharField(blank=True, max_length=120, verbose_name='Région/État')),
                ('postal_code', models.CharField(blank=True, max_length=30, verbose_name='Code postal')),
                ('country', models.CharField(default='', max_length=120, verbose_name='Pays')),
                ('id_type', models.CharField(choices=[('id_card', 'Carte d’identité'), ('passport', 'Passeport'), ('license', 'Permis de conduire')], max_length=20, verbose_name='Type de pièce')),
                ('id_number', models.CharField(max_length=120, verbose_name='Numéro de la pièce')),
                ('id_expiry', models.DateField(blank=True, null=True, verbose_name='Date d’expiration')),
                ('motivation', models.TextField(blank=True, verbose_name='Motivation')),
                ('emergency_contact', models.CharField(blank=True, max_length=255, verbose_name='Contact d’urgence (nom & tél.)')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('needs_changes', 'À corriger'), ('approved', 'Approuvée'), ('rejected', 'Refusée')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True, verbose_name='Note du reviewer')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='VolunteerApplicationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('id_front', 'Pièce d’identité — Recto'), ('id_back', 'Pièce d’identité — Verso'), ('selfie', 'Selfie avec la pièce'), ('proof_address', 'Justificatif de domicile'), ('criminal_record', 'Casier judiciaire / extrait'), ('other', 'Autre document')], max_length=30, verbose_name='Type de document')),
                ('file', models.FileField(upload_to=staff.models.application_upload_to, verbose_name='Fichier')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Refusé')], default='pending', max_length=20)),
                ('reviewer_note', models.TextField(blank=True, verbose_name='Note du reviewer')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='staff.volunteerapplication')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='AuthorizationKeyUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(max_length=64)),
                ('object_pk', models.CharField(blank=True, max_length=64)),
                ('object_repr', models.CharField(blank=True, max_length=200)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=400)),
                ('success', models.BooleanField(default=False)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uses', to='staff.authorizationkey')),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-used_at'],
                'indexes': [models.Index(fields=['used_at', 'action'], name='staff_autho_used_at_2576c0_idx')],
            },
        ),
        migrations.CreateModel(
            name='MissionSignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('invited', 'Invité'), ('pending', 'En attente'), ('accepted', 'Accepté'), ('declined', 'Refusé'), ('cancelled', 'Annulé')], default='invited', max_length=16)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mission_invitations_sent', to=settings.AUTH_USER_MODEL)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signups', to='staff.mission')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mission_signups', to='accounts.volunteer')),
            ],
            options={
                'indexes': [models.Index(fields=['volunteer', 'status'], name='staff_missi_volunte_ce6c05_idx'), models.Index(fields=['mission', 'status'], name='staff_missi_mission_7b2b8a_idx')],
                'unique_together': {('mission', 'volunteer')},
            },
        ),
        migrations.AddIndex(
            model_name='volunteerapplication',
            index=models.Index(fields=['user', 'status'], name='staff_volun_user_id_26d497_idx'),
        ),
        migrations.AddIndex(
            model_name='volunteerapplication',
            index=models.Index(fields=['-submitted_at'], name='staff_volun_submitt_3be706_idx'),
        ),
        migrations.AddConstraint(
            model_name='volunteerapplication',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'approved')), fields=('user',), name='uniq_approved_application_per_user'),
        ),
        migrations.AddConstraint(
            model_name='volunteerapplication',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'needs_changes'])), fields=('user',), name='uniq_open_application_per_user'),
        ),
    ]
