# Generated by Django 5.2.4 on 2025-09-05 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_city_sitestats'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missions', to='core.city'),
        ),
    ]
