# Generated by Django 5.2.4 on 2025-09-16 23:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0001_initial'),
        ('staff', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hoursentry',
            name='mission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hours_entries', to='staff.mission'),
        ),
        migrations.AddField(
            model_name='hoursentryproof',
            name='hours_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proofs', to='accounts.hoursentry'),
        ),
        migrations.AddField(
            model_name='userdocument',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='volunteers', to='core.city'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='phoneverification',
            name='volunteer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_verifications', to='accounts.volunteer'),
        ),
        migrations.AddField(
            model_name='hoursentry',
            name='volunteer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hours_entries', to='accounts.volunteer'),
        ),
        migrations.AddField(
            model_name='availability',
            name='volunteer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='accounts.volunteer'),
        ),
        migrations.AddField(
            model_name='activityitem',
            name='volunteer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='accounts.volunteer'),
        ),
        migrations.AddField(
            model_name='volunteerskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='accounts.skill'),
        ),
        migrations.AddField(
            model_name='volunteerskill',
            name='volunteer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_skills', to='accounts.volunteer'),
        ),
        migrations.AddIndex(
            model_name='phoneverification',
            index=models.Index(fields=['volunteer', 'expires_at'], name='accounts_ph_volunte_ae9875_idx'),
        ),
        migrations.AddConstraint(
            model_name='hoursentry',
            constraint=models.CheckConstraint(condition=models.Q(('hours__gt', 0)), name='hours_positive'),
        ),
        migrations.AddConstraint(
            model_name='hoursentry',
            constraint=models.UniqueConstraint(fields=('volunteer', 'mission', 'date'), name='uniq_hours_by_volunteer_mission_date'),
        ),
        migrations.AlterUniqueTogether(
            name='availability',
            unique_together={('volunteer', 'day', 'slot')},
        ),
        migrations.AlterUniqueTogether(
            name='volunteerskill',
            unique_together={('volunteer', 'skill')},
        ),
    ]
