# Generated by Django 5.2.4 on 2025-09-01 23:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerskill',
            name='proof',
            field=models.FileField(blank=True, null=True, upload_to='skill_proofs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp'])]),
        ),
    ]
