# Generated by Django 5.2.4 on 2025-09-02 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_volunteerskill_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='name_last_changed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
