# Generated by Django 5.2.4 on 2025-09-04 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_emailchangerequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=30)),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_verifications', to='accounts.volunteer')),
            ],
            options={
                'indexes': [models.Index(fields=['volunteer', 'expires_at'], name='accounts_ph_volunte_ae9875_idx')],
            },
        ),
    ]
